# Generated by Django 4.2 on 2023-09-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('business', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('est_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance', models.FloatField()),
            ],
        ),
    ]
