# Generated by Django 4.2 on 2023-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_food_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.FloatField(),
        ),
    ]
